<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>P8105 Fall 2023 Final Project Proposal</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="BRFSS-Analysis.html">US Overview</a>
</li>
<li>
  <a href="Data-Sources.html">Data Sources</a>
</li>
<li>
  <a href="Yi-data-clean.html">Preliminary Analysis</a>
</li>
<li>
  <a href="p8105-Final-model-analysis.html">Exploratory Analysis</a>
</li>
<li>
  <a href="Conclusion.html">Conclusion</a>
</li>
<li>
  <a href="https://github.com/Jodygao/p8105_Final-project_R.git">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">P8105 Fall 2023 Final Project Proposal</h1>

</div>


<div id="distribution-plot" class="section level2">
<h2>Distribution Plot</h2>
<pre class="r"><code># Histogram for BMI
ggplot(obesity, aes(x = bmi)) + 
  geom_histogram(binwidth = 1, fill = &quot;blue&quot;, color = &quot;black&quot;) + 
  labs(title = &quot;Distribution of BMI&quot;, x = &quot;BMI&quot;, y = &quot;Count&quot;) + 
  theme_minimal()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/data%20distribution%20plots-1.png" width="672" /></p>
<pre class="r"><code># Density plot for BMI
ggplot(obesity, aes(x = bmi)) + 
  geom_density(fill = &quot;blue&quot;, alpha = 0.5) + 
  labs(title = &quot;Density Plot for BMI&quot;, x = &quot;BMI&quot;, y = &quot;Density&quot;) + 
  theme_minimal()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/data%20distribution%20plots-2.png" width="672" /></p>
<pre class="r"><code># Boxplot for BMI
ggplot(obesity, aes(y = bmi, x = 1)) + 
  geom_boxplot(fill = &quot;blue&quot;, alpha = 0.5) + 
  labs(title = &quot;Boxplot for BMI&quot;, x = &quot;&quot;, y = &quot;BMI&quot;) + 
  theme_minimal()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/data%20distribution%20plots-3.png" width="672" /></p>
<p>The histogram and density plot indicate that the distribution of
<code>BMI</code> is right-skewed, which is a common observation in
health-related data.</p>
<p>When the response variable in a regression model, BMI, in our case,
is not normally distributed, we took a common approach is to apply a
transformation to achieve normality. The logarithmic transformation is
particularly useful because it is a monotonic transformation that can
handle positive skewness by compressing the long tail and expanding the
lower end of the distribution. This can make the distribution more
symmetric and more closely approximate the normal distribution, which
meets the assumptions of linear regression.</p>
<p>By transforming <code>BMI</code> using the natural logarithm, we can
stabilize the variance (homoscedasticity) and make the relationship
between the predictors and the response variable more linear. This is
beneficial because linear regression assumes a linear relationship
between the predictors and the outcome variable.</p>
</div>
<div
id="cross-validation-and-model-comparison-for-predicting-bmi-based-on-fast-food-frequency"
class="section level2">
<h2>Cross-Validation and Model Comparison for Predicting BMI Based on
Fast Food Frequency</h2>
<p>First, we compare the three models for predictor fast food
frequency</p>
<pre class="r"><code>cv_df = 
  obesity |&gt; 
  crossv_mc(n = 100) |&gt; 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
cv_results =
  cv_df |&gt; 
  mutate(
    model_fast_crude = map(train, \(df) lm(log(bmi) ~ freq_fast_food, data = df) ),
    model_fast_adjusted = map(train, \(df) lm(log(bmi) ~ freq_fast_food+age+gender+marital_status+ race+education+income_to_poverty, data = df)),
    model_fast_inter = map(train, \(df) lm(log(bmi) ~ freq_fast_food*education+freq_fast_food*income_to_poverty+freq_fast_food+age+gender+marital_status+ race+education+income_to_poverty, data = df))
  ) |&gt; 
  mutate(
    rmse_fast_crude = map2_dbl(model_fast_crude, test, \(mod, df) rmse(mod, df)),
    rmse_fast_adjusted = map2_dbl(model_fast_adjusted, test, \(mod, df) rmse(mod, df)),
    rmse_fast_inter = map2_dbl(model_fast_inter, test, \(mod, df) rmse(mod, df))
  )</code></pre>
</div>
<div id="plot-of-model-comparison-of-fast-food-frequency"
class="section level2">
<h2>Plot of Model Comparison of Fast Food Frequency</h2>
<pre class="r"><code>cv_results |&gt; 
  select(starts_with(&quot;rmse&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;
  ) |&gt; 
  group_by(model_type) |&gt; 
  summarize(m_rmse = mean(rmse))</code></pre>
<pre><code>## # A tibble: 3 × 2
##   model_type    m_rmse
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 fast_adjusted  0.320
## 2 fast_crude     0.490
## 3 fast_inter     0.342</code></pre>
<pre class="r"><code>cv_results |&gt; 
  select(starts_with(&quot;rmse&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;
  ) |&gt; 
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/model%20comparison-1.png" width="672" /></p>
<ul>
<li><code>fast_adjusted</code> model has a lower median with most of its
data concentrated at the lower end of the rmse scale, which suggests
better predictive performance for most of its predictions compared to
the other models.</li>
<li><code>fast_crude</code> model has a wider spread of values,
indicating less consistency in predictive performance.</li>
<li><code>fast_inter</code> has most of its data concentrated at the low
end like fast_adjusted, but the long tail indicates there are also quite
a few cases where its predictions are much worse.</li>
</ul>
<p>Considering this, <code>fast_adjusted</code> seems to be the best
model overall due to its concentration of lower rmse values, although
<code>fast_inter</code> may also perform similarly well for the majority
of predictions but has some predictions with high error.</p>
<p>Interpretaion: For one unit increase in number of meals from fast
food or pizza place, the bmi will decrease by 0.0026 kg/m^2, while
adjusting for all other covariate in the model.</p>
</div>
<div
id="cross-validation-and-model-comparison-for-predicting-bmi-based-on-sendendary-activity"
class="section level2">
<h2>Cross-Validation and Model Comparison for Predicting BMI Based on
Sendendary Activity</h2>
<pre class="r"><code># Histogram and Density Plot for Sedentary Activity
ggplot(obesity, aes(x = sedentary_activity)) +
  geom_histogram(binwidth = 10, fill = &quot;green&quot;, color = &quot;black&quot;, alpha = 0.7) + 
  geom_density(alpha = 0.2, adjust = 1/5) + 
  labs(title = &quot;Distribution of Sedentary Activity&quot;, x = &quot;Sedentary Activity&quot;, y = &quot;Density&quot;) +
  theme_minimal()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/distribution-1.png" width="672" /></p>
<div id="step-1-model-building-for-sedentary-activity-with-logbmi"
class="section level3">
<h3>Step 1: Model building for sedentary activity with log(BMI)</h3>
<pre class="r"><code>cv_df_sedentary = 
  obesity |&gt; 
  crossv_mc(n = 100) |&gt; 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

cv_results_sedentary =
  cv_df_sedentary |&gt; 
  mutate(
    model_sed_crude = map(train, \(df) lm(log(bmi) ~ sedentary_activity, data = df)),
    model_sed_adjusted = map(train, \(df) lm(log(bmi) ~ sedentary_activity+age+gender+marital_status+race+education+income_to_poverty, data = df)),
    model_sed_inter = map(train, \(df) lm(log(bmi) ~ sedentary_activity*education+sedentary_activity*income_to_poverty+sedentary_activity+age+gender+marital_status+race+education+income_to_poverty, data = df))
  ) |&gt; 
  mutate(
    rmse_sed_crude = map2_dbl(model_sed_crude, test, \(mod, df) rmse(mod, df)),
    rmse_sed_adjusted = map2_dbl(model_sed_adjusted, test, \(mod, df) rmse(mod, df)),
    rmse_sed_inter = map2_dbl(model_sed_inter, test, \(mod, df) rmse(mod, df))
  )</code></pre>
<pre class="r"><code>cv_results_sedentary |&gt; 
  select(starts_with(&quot;rmse_sed&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_sed_&quot;
  ) |&gt; 
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/cross%20validation%20comparison-1.png" width="672" /></p>
</div>
</div>
<div id="summary-of-cross-validation-results--sendendary-activity"
class="section level2">
<h2>Summary of Cross validation Results- Sendendary Activity</h2>
<pre class="r"><code>rmse_summary = cv_results_sedentary |&gt; 
  select(starts_with(&quot;rmse_sed&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_sed_&quot;
  ) |&gt; 
  group_by(model_type) |&gt; 
  summarize(m_rmse = mean(rmse))
kable(rmse_summary, format = &quot;markdown&quot;, caption = &quot;Summary of RMSE for Sedentary Models&quot;)</code></pre>
<table>
<caption>Summary of RMSE for Sedentary Models</caption>
<thead>
<tr class="header">
<th align="left">model_type</th>
<th align="right">m_rmse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">adjusted</td>
<td align="right">0.2354447</td>
</tr>
<tr class="even">
<td align="left">crude</td>
<td align="right">0.2374056</td>
</tr>
<tr class="odd">
<td align="left">inter</td>
<td align="right">0.2353406</td>
</tr>
</tbody>
</table>
<p>In the context of these models, a lower RMSE indicates a more
accurate prediction of BMI from the predictors used in the model.</p>
<p>The cross-validation results show that the mean RMSE for the adjusted
and inter (interaction) models are both 0.235, while the crude model has
a slightly higher RMSE of 0.237. In this case, both the adjusted and
inter models perform slightly better than the crude model, as indicated
by their lower RMSE values, which means they are, on average, closer to
the true BMI values when log-transformed.</p>
<p>A valid reason we choose the adjusted model over the inter model,
despite having the same RMSE, could be due to its simplicity and
interpretability. The adjusted model includes additional covariates
(age, gender, marital status, race, education, and income to poverty
ratio) that are expected to be related to BMI based on previous research
or theoretical considerations. Including these covariates allows the
model to account for more variability in BMI that is explained by these
factors.</p>
<p>Moreover, while interaction terms in the inter model may capture the
combined effects of sedentary activity with other variables, they can
make the model more complex and harder to interpret.</p>
<p>We proceed the model statistics in adjusted model for sedentary
activity.</p>
<div id="adjusted-model" class="section level3">
<h3>Adjusted Model</h3>
<pre class="r"><code># Step 1: Generate new data for plotting
new_data &lt;- with(obesity, expand.grid(
  sedentary_activity = seq(min(sedentary_activity, na.rm = TRUE), max(sedentary_activity, na.rm = TRUE), length.out = 100),
  age = mean(age, na.rm = TRUE),
  gender = &quot;Female&quot;, 
  marital_status = &quot;Married&quot;, 
  race = &quot;White&quot;, 
  education = &quot;Less than 9th grade&quot;, 
  income_to_poverty = mean(income_to_poverty, na.rm = TRUE)
))

# Step 2: Predict log(BMI) using the adjusted model and the new data
adjusted_model &lt;- cv_results_sedentary$model_sed_adjusted[[1]]
new_data$log_bmi_pred &lt;- predict(adjusted_model, newdata = new_data)

# Step 3: Create the plot
ggplot(new_data, aes(x = sedentary_activity, y = log_bmi_pred)) +
  geom_line(color = &quot;blue&quot;) +
  labs(title = &quot;Predicted Log BMI vs Sedentary Activity&quot;,
       x = &quot;Sedentary Activity&quot;,
       y = &quot;Predicted Log BMI&quot;) +
  theme_minimal()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/model%20plot%20for%20adjusted%20model-1.png" width="672" /></p>
<pre class="r"><code>best_model_summary &lt;- cv_results_sedentary$model_sed_adjusted[[1]] %&gt;% summary()

# Summary of Adjusted Model
print(best_model_summary)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(bmi) ~ sedentary_activity + age + gender + marital_status + 
##     race + education + income_to_poverty, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.73319 -0.15406 -0.00803  0.14553  1.12462 
## 
## Coefficients:
##                                            Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                               3.382e+00  1.881e-02 179.851  &lt; 2e-16
## sedentary_activity                        1.768e-04  1.908e-05   9.267  &lt; 2e-16
## age                                       5.789e-05  2.437e-04   0.238 0.812250
## genderMale                               -4.739e-02  7.520e-03  -6.302 3.26e-10
## marital_statusNever married              -2.811e-02  1.076e-02  -2.611 0.009048
## marital_statusWidowed/Divorced/Separated -3.198e-02  9.614e-03  -3.326 0.000888
## raceMexican American                     -6.548e-04  1.272e-02  -0.051 0.958938
## raceOther                                -1.754e-01  1.546e-02 -11.344  &lt; 2e-16
## raceOther Hispanic                       -1.627e-02  1.339e-02  -1.215 0.224283
## raceWhite                                -3.604e-02  9.331e-03  -3.863 0.000114
## educationHigh school graduate             1.395e-02  1.186e-02   1.176 0.239522
## educationLess than 9th grade              1.640e-02  1.619e-02   1.013 0.311228
## educationSome college or AA degree        1.043e-02  1.175e-02   0.888 0.374786
## income_to_poverty                         9.416e-04  2.748e-03   0.343 0.731880
##                                             
## (Intercept)                              ***
## sedentary_activity                       ***
## age                                         
## genderMale                               ***
## marital_statusNever married              ** 
## marital_statusWidowed/Divorced/Separated ***
## raceMexican American                        
## raceOther                                ***
## raceOther Hispanic                          
## raceWhite                                ***
## educationHigh school graduate               
## educationLess than 9th grade                
## educationSome college or AA degree          
## income_to_poverty                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2346 on 4023 degrees of freedom
##   (5073 observations deleted due to missingness)
## Multiple R-squared:  0.06215,    Adjusted R-squared:  0.05912 
## F-statistic: 20.51 on 13 and 4023 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="residual-plot-for-adjusted-model---sedentary-activity"
class="section level2">
<h2>Residual Plot for Adjusted Model - Sedentary Activity</h2>
<pre class="r"><code>best_model &lt;- cv_results_sedentary$model_sed_adjusted[[1]]
best_model_residuals &lt;- resid(best_model)
best_model_fitted &lt;- fitted(best_model)

residual_plot &lt;- ggplot() +
  geom_point(aes(x = best_model_fitted, y = best_model_residuals)) +
  geom_hline(yintercept = 0, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Residuals vs Fitted Values for Interaction Model&quot;,
       x = &quot;Fitted Values&quot;,
       y = &quot;Residuals&quot;) +
  theme_minimal() +
  geom_smooth(aes(x = best_model_fitted, y = best_model_residuals), method = &quot;loess&quot;, se = FALSE)

print(residual_plot)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/residual%20plot%20for%20activity-1.png" width="672" /></p>
<p><strong>Coefficients Interpretation on Log Scale</strong> -
<code>Intercept</code>: The estimated <code>log(BMI)</code> is
approximately 3.366 when all predictor variables are held at zero. To
interpret this on the original BMI scale, you would calculate
exp(3.366). This value represents the estimated BMI for the baseline
categories of all categorical predictors (usually the most common or
reference category) and zero for continuous predictors.</p>
<ul>
<li><p><code>Sedentary Activity</code>: The coefficient for sedentary
activity is positive (0.0001905) and statistically significant. This
suggests that for each unit increase in sedentary activity, the log(BMI)
increases by this amount. To interpret the effect on the original BMI
scale, consider that a small increase in the <code>log(BMI)</code>
corresponds to a percentage increase in BMI. Specifically, a one-unit
increase in sedentary activity is associated with approximately a
0.01905% increase in BMI.</p></li>
<li><p><code>Other Predictors</code>: Similarly, for other continuous
predictors like age, the coefficient represents the percentage change in
BMI for a one-unit increase in that predictor. For categorical
predictors like gender, marital status, and race, the coefficients
represent the percentage difference in BMI compared to the reference
category.</p></li>
<li><p><code>Model Fit and R-squared</code>: The <code>R-squared</code>
value (0.06851) indicates that about 6.851% of the variability in
log-transformed BMI is explained by the model. While this might seem
low, it’s not uncommon in behavioral and social science research where
many unmeasured factors can influence the outcome.</p></li>
</ul>
<p><strong>Statistical Significance</strong> The significance of the
coefficients suggests that these factors have a statistically
significant association with BMI. However, the magnitude of these
effects might be small, especially for variables like age and
income_to_poverty ratio.</p>
<p><strong>Overall Interpretation</strong> The significant predictors in
the model, like <code>sedentary activity</code> and <code>gender</code>,
indicate factors that are associated with <code>BMI</code>. However, the
small R-squared value suggests that many other factors not included in
the model also influence <code>BMI</code>. Given that the response
variable is log-transformed, the interpretation is in terms of
percentage change (for continuous predictors) or relative percentage
difference (for categorical predictors) in BMI.</p>
</div>
<div
id="cross-validation-and-model-buildup-for-predicting-bmi-based-on-frozen-fast-food-frequency"
class="section level1">
<h1>Cross-Validation and Model Buildup for Predicting BMI Based on
Frozen Fast Food Frequency</h1>
<pre class="r"><code>cv_df_frozen = 
  obesity |&gt; 
  crossv_mc(n = 100) |&gt; 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )</code></pre>
<div id="model-building---logbmi" class="section level2">
<h2>Model building - log(BMI)</h2>
<pre class="r"><code>cv_results_frozen =
  cv_df_frozen |&gt; 
  mutate(
    model_frozen_crude = map(train, \(df) lm(log(bmi) ~ freq_frozen, data = df)),
    model_frozen_adjusted = map(train, \(df) lm(log(bmi) ~ freq_frozen + age + gender + marital_status + race + education + income_to_poverty, data = df)),
    model_frozen_inter = map(train, \(df) lm(log(bmi) ~ freq_frozen * education + freq_frozen * income_to_poverty + freq_frozen + age + gender + marital_status + race + education + income_to_poverty, data = df))
  ) |&gt; 
  mutate(
    rmse_frozen_crude = map2_dbl(model_frozen_crude, test, \(mod, df) rmse(mod, df)),
    rmse_frozen_adjusted = map2_dbl(model_frozen_adjusted, test, \(mod, df) rmse(mod, df)),
    rmse_frozen_inter = map2_dbl(model_frozen_inter, test, \(mod, df) rmse(mod, df))
  )</code></pre>
</div>
<div id="cross-validation-comparison" class="section level2">
<h2>Cross-validation Comparison</h2>
<pre class="r"><code>cv_results_frozen |&gt; 
  select(starts_with(&quot;rmse_frozen&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_frozen_&quot;
  ) |&gt; 
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<pre class="r"><code>cv_results_frozen |&gt; 
  select(starts_with(&quot;rmse_frozen&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_frozen_&quot;
  ) |&gt; 
  group_by(model_type) |&gt; 
  summarize(m_rmse = mean(rmse))</code></pre>
<pre><code>## # A tibble: 3 × 2
##   model_type m_rmse
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 adjusted    0.255
## 2 crude       0.309
## 3 inter       0.341</code></pre>
<p>According to the violin plot of the RMSE distribution for each model,
the adjusted model consistently shows a concentrated distribution of
lower RMSE values, meaning it has a superior predictive performance
relative to the crude and interaction models. This observation is
confirmed by the summary of cross-validation results, which indicates
that the adjusted model has the lowest mean RMSE of 0.243, compared to
0.309 for the crude model and 0.336 for the interaction model. Since
lower values mean better model performance, the adjusted model has the
best model performance among these three models.</p>
</div>
<div id="adjusted-model-1" class="section level2">
<h2>Adjusted Model</h2>
<pre class="r"><code>obesity$marital_status &lt;- factor(obesity$marital_status)
obesity$race &lt;- factor(obesity$race)
obesity$education &lt;- factor(obesity$education)

new_data_frozen &lt;- expand.grid(
  freq_frozen = seq(min(obesity$freq_frozen, na.rm = TRUE), max(obesity$freq_frozen, na.rm = TRUE), length.out = 100),
  age = mean(obesity$age, na.rm = TRUE),
  gender = levels(obesity$gender)[1],
  marital_status = levels(obesity$marital_status)[1],
  race = levels(obesity$race)[1],
  education = levels(obesity$education)[1],
  income_to_poverty = mean(obesity$income_to_poverty, na.rm = TRUE)
)

str(new_data_frozen)</code></pre>
<pre><code>## &#39;data.frame&#39;:    100 obs. of  7 variables:
##  $ freq_frozen      : num  0 67.3 134.7 202 269.3 ...
##  $ age              : num  35.6 35.6 35.6 35.6 35.6 ...
##  $ gender           : Factor w/ 1 level &quot;Female&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ marital_status   : Factor w/ 1 level &quot;Married&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ race             : Factor w/ 1 level &quot;Black&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ education        : Factor w/ 1 level &quot;9-11th grade&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ income_to_poverty: num  2.42 2.42 2.42 2.42 2.42 ...
##  - attr(*, &quot;out.attrs&quot;)=List of 2
##   ..$ dim     : Named int [1:7] 100 1 1 1 1 1 1
##   .. ..- attr(*, &quot;names&quot;)= chr [1:7] &quot;freq_frozen&quot; &quot;age&quot; &quot;gender&quot; &quot;marital_status&quot; ...
##   ..$ dimnames:List of 7
##   .. ..$ freq_frozen      : chr [1:100] &quot;freq_frozen=   0.00000&quot; &quot;freq_frozen=  67.33333&quot; &quot;freq_frozen= 134.66667&quot; &quot;freq_frozen= 202.00000&quot; ...
##   .. ..$ age              : chr &quot;age=35.62302&quot;
##   .. ..$ gender           : chr &quot;gender=Female&quot;
##   .. ..$ marital_status   : chr &quot;marital_status=Married&quot;
##   .. ..$ race             : chr &quot;race=Black&quot;
##   .. ..$ education        : chr &quot;education=9-11th grade&quot;
##   .. ..$ income_to_poverty: chr &quot;income_to_poverty=2.42299&quot;</code></pre>
<div id="predict-logbmi" class="section level3">
<h3>Predict log(BMI)</h3>
<pre class="r"><code>adjusted_model_frozen &lt;- cv_results_frozen$model_frozen_adjusted[[1]]
new_data_frozen$log_bmi_pred &lt;- predict(adjusted_model_frozen, newdata = new_data_frozen)

# Plot the predicted values
ggplot(new_data_frozen, aes(x = freq_frozen, y = log_bmi_pred)) +
  geom_line(color = &quot;purple&quot;) +
  labs(title = &quot;Predicted Log BMI vs Frozen Fast Food Frequency&quot;,
       x = &quot;Frozen Fast Food Frequency&quot;,
       y = &quot;Predicted Log BMI&quot;) +
  theme_minimal()</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="best-adjusted-model-from-cross-validation"
class="section level3">
<h3>Best ‘Adjusted’ Model from Cross-validation</h3>
<pre class="r"><code>best_adjusted_model_summary &lt;- cv_results_frozen$model_frozen_adjusted[[1]] %&gt;% summary()

# Print the summary which includes coefficients, R-squared, p-values...
print(best_adjusted_model_summary)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(bmi) ~ freq_frozen + age + gender + marital_status + 
##     race + education + income_to_poverty, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.77950 -0.16042 -0.00957  0.14804  1.08649 
## 
## Coefficients:
##                                            Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                               3.425e+00  1.852e-02 184.908  &lt; 2e-16
## freq_frozen                              -5.864e-05  3.588e-05  -1.634  0.10229
## age                                       2.015e-04  2.478e-04   0.813  0.41612
## genderMale                               -4.636e-02  7.628e-03  -6.078 1.33e-09
## marital_statusNever married              -2.089e-02  1.082e-02  -1.931  0.05360
## marital_statusWidowed/Divorced/Separated -2.197e-02  9.743e-03  -2.255  0.02418
## raceMexican American                     -1.438e-02  1.289e-02  -1.116  0.26459
## raceOther                                -1.825e-01  1.562e-02 -11.685  &lt; 2e-16
## raceOther Hispanic                       -3.588e-02  1.347e-02  -2.664  0.00775
## raceWhite                                -3.019e-02  9.437e-03  -3.199  0.00139
## educationHigh school graduate             8.532e-03  1.201e-02   0.710  0.47745
## educationLess than 9th grade              1.591e-05  1.640e-02   0.001  0.99923
## educationSome college or AA degree        2.756e-02  1.188e-02   2.321  0.02035
## income_to_poverty                         8.040e-04  2.780e-03   0.289  0.77244
##                                             
## (Intercept)                              ***
## freq_frozen                                 
## age                                         
## genderMale                               ***
## marital_statusNever married              .  
## marital_statusWidowed/Divorced/Separated *  
## raceMexican American                        
## raceOther                                ***
## raceOther Hispanic                       ** 
## raceWhite                                ** 
## educationHigh school graduate               
## educationLess than 9th grade                
## educationSome college or AA degree       *  
## income_to_poverty                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2391 on 4065 degrees of freedom
##   (5031 observations deleted due to missingness)
## Multiple R-squared:  0.04484,    Adjusted R-squared:  0.04178 
## F-statistic: 14.68 on 13 and 4065 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The best-fitting model, based on the cross-validation results, is the
adjusted model. Thus, a detailed examination was conducted, and its
summary statistics indicate that: The Intercept is estimated at 3.409 on
the log scale. The coefficient for frozen fast food frequency is
-4.291e-06 with a p-value of 0.86427, this suggests that the number of
frozen fast food meals consumed does not have a statistically
significant effect on BMI in this model. Other covariates, such as
gender and race show significant associations with BMI, with gender
(Male) and race (Other) showing a strong negative association with BMI.
The R-squared value of 0.03455 indicates that approximately 3.455% of
the variability in the log-transformed BMI is explained by the
model.</p>
</div>
<div id="residuals-plot" class="section level3">
<h3>Residuals Plot</h3>
<pre class="r"><code>adjusted_model &lt;- cv_results_frozen$model_frozen_adjusted[[1]]
adjusted_model_residuals &lt;- resid(adjusted_model)
adjusted_model_fitted &lt;- fitted(adjusted_model)

# Plot the residuals against the fitted values
residual_plot &lt;- ggplot() +
  geom_point(aes(x = adjusted_model_fitted, y = adjusted_model_residuals)) +
  geom_hline(yintercept = 0, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Residuals vs Fitted Values for Adjusted Model&quot;,
       x = &quot;Fitted Values&quot;,
       y = &quot;Residuals&quot;) +
  theme_minimal() +
  geom_smooth(aes(x = adjusted_model_fitted, y = adjusted_model_residuals), method = &quot;loess&quot;, se = FALSE)

# Print the residual plot
print(residual_plot)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The residuals plot against fitted values provides insight into the
adequacy of the model fit. The presence of a random scatter of residuals
around the horizontal line at zero suggests no obvious issues with
non-linearity or heteroscedasticity. However, the slight curvature in
the LOESS line and the increasing spread of residuals at higher fitted
values could imply potential model misspecification or the need for a
variable transformation to address heteroscedasticity.</p>
</div>
</div>
<div id="conclusion-of-frozen-food-consumption-on-bmi"
class="section level2">
<h2>Conclusion of frozen food consumption on BMI</h2>
<p>Overall, our analysis suggests that while frozen fast food
consumption frequency does not significantly predict BMI, other factors
such as gender and race do have significant associations. The small
R-squared value implies that other unmeasured factors also play a role
in influencing BMI, which are not captured by this model.</p>
<p>The relatively stable variance in residuals suggests that the linear
model is a reasonable fit for the data, although there is room for
improvement. Future modeling efforts might explore the inclusion of
non-linear terms, additional interaction terms, or other predictor
variables to enhance the model’s explanatory power.</p>
</div>
</div>
<div id="regression-models-and-diagnostics" class="section level1">
<h1>Regression Models and Diagnostics</h1>
<div id="model1-logbmifreq_fast" class="section level2">
<h2>Model1: log(BMI)=freq_fast</h2>
<pre class="r"><code>freq_fast_crude = lm(log(bmi) ~ freq_fast_food, data = obesity)

obesity |&gt; modelr::add_residuals(freq_fast_crude) |&gt; 
  ggplot(aes(sample = resid))+stat_qq()+stat_qq_line()</code></pre>
<pre><code>## Warning: Removed 2345 rows containing non-finite values (`stat_qq()`).</code></pre>
<pre><code>## Warning: Removed 2345 rows containing non-finite values (`stat_qq_line()`).</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="model2-logbmisedentary_activity" class="section level2">
<h2>Model2: log(BMI)=sedentary_activity</h2>
<pre class="r"><code>inactivity_crude = lm(log(bmi) ~ sedentary_activity, data = obesity)

obesity |&gt; modelr::add_residuals(inactivity_crude) |&gt; 
  ggplot(aes(sample = resid))+stat_qq()+stat_qq_line()</code></pre>
<pre><code>## Warning: Removed 3879 rows containing non-finite values (`stat_qq()`).</code></pre>
<pre><code>## Warning: Removed 3879 rows containing non-finite values (`stat_qq_line()`).</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="model3-logbmifreqence-of-frozen" class="section level2">
<h2>Model3: log(BMI)=freqence of frozen</h2>
<pre class="r"><code>freq_frozen_crude = lm(log(bmi) ~ freq_frozen, data = obesity)


obesity |&gt; modelr::add_residuals(freq_frozen_crude) |&gt; 
  ggplot(aes(sample = resid))+stat_qq()+stat_qq_line()</code></pre>
<pre><code>## Warning: Removed 38 rows containing non-finite values (`stat_qq()`).</code></pre>
<pre><code>## Warning: Removed 38 rows containing non-finite values (`stat_qq_line()`).</code></pre>
<p><img src="p8105-Final-model-analysis_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
