<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Final report</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Data-Sources.html">Data Sources</a>
</li>
<li>
  <a href="Yi-data-clean.html">Preliminary Analysis</a>
</li>
<li>
  <a href="p8105-Final-model-analysis.html">Exploratory Analysis</a>
</li>
<li>
  <a href="https://8105final.shinyapps.io/shiny/">Shiny App</a>
</li>
<li>
  <a href="Conclusion.html">Conclusion</a>
</li>
<li>
  <a href="Report.html">Final Report</a>
</li>
<li>
  <a href="https://github.com/Jodygao/p8105_Final-project_R.git">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Final report</h1>

</div>


<p>“Multifaceted Analysis of Obesity: Exploring the Interplay of Diet,
Sedentary Lifestyle, and Socio-Demographic Factors in the United States
from 2017-2020”</p>
<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>The increasing prevalence of obesity cases in the United States is
becoming a serious public health issue and bringing up lots of adverse
comorbidities. The problem that comes with obesity exists not just on an
individual level but is more troublesome as it can lead to substantial
effects on the overall healthcare system’s performance and affect
economies across the country. When we talk about obesity nowadays, we
can not stop thinking of the burden that associated with it. According
to a National Survey published by Forbes Health, between 2017 and 2020,
around 41.9% of adults in the United States were obese1. With almost
half of the adults being obese, Obesity was considered a national
epidemic. Concerns like chronic diseases, type 2 diabetes,
cardiovascular conditions, and certain forms of cancer, that are linked
with obesity, can easily lead to heightened mortality rates and
diminished quality of life. The causes of obesity are diverse and
complex2, involving genetics, societal, and environmental factors but
addressing this public health problem and educating the importance of
personal wellness among the obese population in the U.S. is in urgent
need.</p>
</div>
<div id="related-workinspiration" class="section level2">
<h2>Related work/Inspiration</h2>
<p>The inspiration for this project comes from a small observation and
pure curiosity. Although it has always been acknowledged that obesity
prevalence is very high in the U.S., it can have many adverse health
effects on one’s overall health and well-being, our awareness of obesity
as a health issue was still initially superficial. However, it deepened
significantly this semester. For most of us in the group, we have a
class running from 5:30-8:30 PM. By the time we finish the class, what
we rely on is McDonald’s, primarily due to its distance to the campus,
low price, and is the one that still opens at that time of the day. This
routine exposure to fast food changed our way of understanding obesity’s
impacts on the public since we constantly see people with big body
images consuming fast food in McDonald’s. The observation led to
curiosity and we wonder about the health consequences of fast-food
consumption and the impact of obesity.</p>
<p>#Initial questions ## Primary Questions: How does the frequency of
fast food consumption relate to the Body Mass Index (BMI) of individuals
in the U.S.? Is there a significant correlation between the consumption
of frozen fast food and BMI? How does sedentary activity impact BMI, and
what is the extent of this impact? ## Evolution of Questions: As we dig
deeper into the project and go into the data analysis section, the
initial questions evolved to accommodate the complexities of dietary
habits and lifestyle choices. The simple correlation between fast food
consumption and BMI was expanded to include other variables like
physical inactivity. The inadequacy of finding significant results in
the initial models led to a deeper exploration of other contributing
factors. This shift prompted a broader approach to understanding the
multifaceted nature of obesity. ## Emerging Questions: Given the
nonsignificant findings in the initial models, new questions emerged:
Are there other dietary or lifestyle factors, beyond fast food
consumption and physical inactivity, that significantly contribute to
obesity? Analysis Driven Questions(For us to consider later): During the
data analysis, our group also brought up questions about the
effectiveness of existing public health strategies in combating obesity.
We still see lots of news and articles saying the prevalence rate
increasing, but not much mentioning the success of any interventions.
What are the gaps in current approaches, and how can they be addressed
more holistically? How can we use the analysis we did and the website we
made to form public health policy changes, for it to better tackle the
root causes of obesity, considering the complex interplay of individual,
societal, and environmental factors?</p>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<div id="data-source" class="section level2">
<h2>Data Source</h2>
<p>Description. The 2017–March 2020 Pre-Pandemic Data Files for this
study are sourced from the National Health and Nutrition Examination
Survey (NHANES), which is an ongoing series of studies designed to
assess the health and nutritional status of the civilian
noninstitutionalized U.S. population. The NHANES data collection
involves interviews and physical examinations, covering a wide range of
health and nutrition-related topics. The data is critical for the
assessment of public health and nutrition and aids in the development of
health policies and research. Special weighting measures have been
applied to the combined dataset to ensure that it reflects the
population and health trends accurately for nationally representative
estimates.</p>
</div>
<div id="data-collection-methodology" class="section level2">
<h2>Data Collection Methodology</h2>
<p>Primary Sampling Units (PSUs). The survey utilizes a multistage
probabilistic sampling design. In the first stage, PSUs are selected
based on stratification by various health and demographic
characteristics. Each PSU is typically a county or a group of contiguous
counties.</p>
<p>Stratification. States are categorized into health groups according
to health index values. PSUs are further divided into major strata
within each health group, which are determined by the urban-rural
population distribution and other locality characteristics.</p>
<p>Sampling Periods. The 2017-2018 and 2019-March 2020 cycles were based
on different 4-year sample designs, with PSUs selected annually from
their respective strata.</p>
<p>Representativeness. The 2017-March 2020 pre-pandemic data file
includes PSUs from the 2017-2018 cycle and 2019-March 2020 data
collection. The combined dataset was calibrated to ensure national
representativeness according to the 2015-2018 sample design, accounting
for changes in population size and other characteristics that determine
major stratum membership.</p>
</div>
</div>
<div id="data-cleaning" class="section level1">
<h1>Data Cleaning</h1>
<p>We first import three files by creating the data import function
(import_df) that reads the data from an .XPT file format. The four
datasets that were merged were: Demographic Variables and Sample Weights
(P_DEMO), Body Measures (P_BMX), Physical Activity (P_PAQ) andDiet
Behavior &amp; Nutrition (P_DBQ). Using a full join on the ‘SEQN’ column
to merge the datasets. Then, we select the specific column that are
meaningful in the process of analysis: <code>SEQN</code>,
<code>RIAGENDR</code>, <code>RIDAGEYR</code>, <code>DMDMARTZ</code>,
<code>INDFMPIR</code>, <code>RIDRETH3</code>, <code>DMDEDUC2</code>,
<code>PAD680</code>, <code>BMXBMI</code>, <code>DBD900</code>, and
<code>DBD910</code>.</p>
<p>Next, we did the data filtering by filtering out specific values from
various column (e.g., ‘77’, ‘99’, ‘.’, ‘7777’, ‘9999’). This step
removed the missing, unknown, and null value from the dataset and only
kept those meaningful values in the dataset.</p>
<p>Furthermore, we rename the columns to more descriptive names like
‘gender’, ‘age’, ‘marital_status’, etc. After this step, we use the
mutate function to transform and categorize several columns: gender:
Categorizing and converting to a factor.</p>
<p>marital_status, race, education: Categorizing different demographic
details. obese: Creating a new variable based on BMI, categorizing
individuals as <code>normal</code> or <code>obese</code>.</p>
<p>The variables in the Final dataset are listed below:
<code>SEQN</code> : Respondent sequence number <code>gender</code>:
Female or male <code>age</code>: Age in years at screening
<code>marital_status</code>: never married, married,
widowed/divorced/separated <code>income_to_poverty</code>: ratio of
family income to poverty <code>race</code>: Mexican American, White,
Black, Other Hispanic <code>bmi</code>: Body Mass Index (kg/m**2)
<code>freq_fast_food</code>: number of meals from fast food or pizza
place <code>freq_frozen</code>: Numbers of frozen meals/pizza in past 30
days <code>sedentary_activity</code>: Minutes sedentary activity
<code>obese</code>: normal, obese</p>
<p>The process effectively cleans and transforms the data, preparing it
for analysis related to obesity. The use of case_match and case_when for
categorizing data is particularly efficient, as it allows for more
readable and interpretable data. This structured approach ensures the
dataset is clean, well-organized, and ready for further statistical
analysis or visualization.</p>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory Analysis</h1>
<pre class="r"><code>obesity_race_filtered = obesity |&gt;  
  filter(!is.na(race) &amp; race != &quot;NA&quot;)

ggplot(obesity_race_filtered, aes(x = race, fill = gender)) +
  geom_bar(position = &quot;dodge&quot;) +
  scale_fill_manual(values = c(&quot;pink&quot;, &quot;lightblue&quot;)) +
  labs(title = &quot;Obesity Prevalence by Race and Gender&quot;,
       x = &quot;Race&quot;,
       y = &quot;Count&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-2-1.png" width="672" />
Interpretation: The bar chart displays the prevalence of obesity across
different racial categories, differentiated by gender. It shows that the
White population has the highest count of obesity cases, with a notable
number of cases in both genders. The Black population follows, with
females being higher than males, whereas the “Other Hispanic” categories
have the lowest count of obesity cases.</p>
<pre class="r"><code>ggplot(subset(obesity, bmi == &quot;obese&quot;), aes(x = age)) +
  geom_histogram(binwidth = 1, fill = &quot;pink&quot;, color = &quot;lightblue&quot;) +
  labs(title = &quot;Age Distribution Among Obese Individuals&quot;,
       x = &quot;Age&quot;,
       y = &quot;Count&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-3-1.png" width="672" />
Interpretation: The histogram indicates that obesity is present across
all age groups, with a relatively uniform distribution from young
adulthood to late middle age. There’s a significant peak in obesity
cases among individuals in their late 50s to early 60s. After this peak,
the number of obese individuals declines sharply for those in the older
age groups.</p>
<pre class="r"><code>ggplot(subset(obesity, bmi == &quot;obese&quot;), aes(y = income_to_poverty, x = &quot;&quot;, fill = bmi)) +
  geom_boxplot() +
  scale_fill_manual(values = c(&quot;pink&quot;)) +
  labs(title = &quot;Income to Poverty Ratio Among Obese Individuals&quot;,
       x = &quot;&quot;,
       y = &quot;Income to Poverty Ratio&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-4-1.png" width="672" />
Interpretation: The box plot shows the distribution of the income to
poverty ratio among obese individuals. The data is spread across a range
of ratios, mostly concentrated between 1 and 4, with the median around
2. This suggests that individuals with obesity come from a range of
economic backgrounds, but there’s a tendency towards lower income to
poverty ratios.</p>
<pre class="r"><code>obesity_sedentary_activity_filtered = obesity |&gt; 
  filter(!is.na(sedentary_activity))

ggplot(obesity_sedentary_activity_filtered, aes(x = sedentary_activity)) +
  geom_histogram(binwidth = 1, fill = &quot;pink&quot;, color = &quot;lightblue&quot;) +
  labs(title = &quot;Sedentary Activity Distribution Among Obese Individuals&quot;,
       x = &quot;Sedentary Activity&quot;,
       y = &quot;Count&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-5-1.png" width="672" />
The majority of obese individuals report sedentary activity levels
between 0 to around 500 minutes, with frequency decreasing as the amount
of sedentary activity increases. There are notable peaks at certain
intervals which may indicate common reporting increments (～250
minutes). Very few individuals report very high levels of sedentary
activity, as seen by the low counts past 1000 minutes.</p>
</div>
<div id="baseline-analysis" class="section level1">
<h1>baseline Analysis</h1>
<pre class="r"><code>gender_summary &lt;- obesity %&gt;%
  count(gender) %&gt;%
  mutate(Percentage = n / sum(n) * 100)

kable(gender_summary, format = &quot;markdown&quot;, caption = &quot;Gender Summary&quot;)</code></pre>
<table>
<caption>Gender Summary</caption>
<thead>
<tr class="header">
<th align="left">gender</th>
<th align="right">n</th>
<th align="right">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="right">5800</td>
<td align="right">50.9308</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="right">5588</td>
<td align="right">49.0692</td>
</tr>
</tbody>
</table>
<pre class="r"><code>marital_status_summary &lt;- obesity %&gt;%
  count(marital_status) %&gt;%
  mutate(Percentage = n / sum(n) * 100)

kable(marital_status_summary, format = &quot;markdown&quot;, caption = &quot;Marital Status Summary&quot;)</code></pre>
<table>
<caption>Marital Status Summary</caption>
<thead>
<tr class="header">
<th align="left">marital_status</th>
<th align="right">n</th>
<th align="right">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Married</td>
<td align="right">4216</td>
<td align="right">37.02143</td>
</tr>
<tr class="even">
<td align="left">Never married</td>
<td align="right">1360</td>
<td align="right">11.94240</td>
</tr>
<tr class="odd">
<td align="left">Widowed/Divorced/Separated</td>
<td align="right">1599</td>
<td align="right">14.04110</td>
</tr>
<tr class="even">
<td align="left">NA</td>
<td align="right">4213</td>
<td align="right">36.99508</td>
</tr>
</tbody>
</table>
<pre class="r"><code>age_summary &lt;- obesity %&gt;%
  summarise(
    Count = n(),
    Unique = n_distinct(age),
    Mean = mean(age, na.rm = TRUE),
    Std_Dev = sd(age, na.rm = TRUE),
    Min = min(age, na.rm = TRUE),
    `25th_Pctl` = quantile(age, 0.25, na.rm = TRUE),
    Median = median(age, na.rm = TRUE),
    `75th_Pctl` = quantile(age, 0.75, na.rm = TRUE),
    Max = max(age, na.rm = TRUE)
  )

kable(age_summary, format = &quot;markdown&quot;, caption = &quot;Age Summary&quot;)</code></pre>
<table>
<caption>Age Summary</caption>
<colgroup>
<col width="9%" />
<col width="10%" />
<col width="13%" />
<col width="13%" />
<col width="6%" />
<col width="15%" />
<col width="10%" />
<col width="15%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Count</th>
<th align="right">Unique</th>
<th align="right">Mean</th>
<th align="right">Std_Dev</th>
<th align="right">Min</th>
<th align="right">25th_Pctl</th>
<th align="right">Median</th>
<th align="right">75th_Pctl</th>
<th align="right">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">11388</td>
<td align="right">79</td>
<td align="right">35.62302</td>
<td align="right">24.24121</td>
<td align="right">2</td>
<td align="right">13</td>
<td align="right">33</td>
<td align="right">57</td>
<td align="right">80</td>
</tr>
</tbody>
</table>
<p>In our study, we found a near-equal distribution of obesity across
genders, with varying prevalence across different marital statuses and a
wide age range.</p>
<pre class="r"><code>income_to_poverty_summary &lt;- obesity %&gt;%
  summarise(
    Count = n(),
    Unique = n_distinct(income_to_poverty),
    Mean = mean(income_to_poverty, na.rm = TRUE),
    Std_Dev = sd(income_to_poverty, na.rm = TRUE),
    Min = min(income_to_poverty, na.rm = TRUE),
    `25th_Pctl` = quantile(income_to_poverty, 0.25, na.rm = TRUE),
    Median = median(income_to_poverty, na.rm = TRUE),
    `75th_Pctl` = quantile(income_to_poverty, 0.75, na.rm = TRUE),
    Max = max(income_to_poverty, na.rm = TRUE)
  )

kable(income_to_poverty_summary, format = &quot;markdown&quot;, caption = &quot;Income to Poverty Summary&quot;)</code></pre>
<table>
<caption>Income to Poverty Summary</caption>
<colgroup>
<col width="9%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="6%" />
<col width="15%" />
<col width="10%" />
<col width="15%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Count</th>
<th align="right">Unique</th>
<th align="right">Mean</th>
<th align="right">Std_Dev</th>
<th align="right">Min</th>
<th align="right">25th_Pctl</th>
<th align="right">Median</th>
<th align="right">75th_Pctl</th>
<th align="right">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">11388</td>
<td align="right">472</td>
<td align="right">2.42299</td>
<td align="right">1.62789</td>
<td align="right">0</td>
<td align="right">1.04</td>
<td align="right">1.99</td>
<td align="right">3.9025</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
<pre class="r"><code>education_summary &lt;- obesity %&gt;%
  count(education) %&gt;%
  mutate(Percentage = n / sum(n) * 100)

kable(education_summary, format = &quot;markdown&quot;, caption = &quot;Education Summary&quot;)</code></pre>
<table>
<caption>Education Summary</caption>
<thead>
<tr class="header">
<th align="left">education</th>
<th align="right">n</th>
<th align="right">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">9-11th grade</td>
<td align="right">763</td>
<td align="right">6.700035</td>
</tr>
<tr class="even">
<td align="left">High school graduate</td>
<td align="right">1722</td>
<td align="right">15.121180</td>
</tr>
<tr class="odd">
<td align="left">Less than 9th grade</td>
<td align="right">475</td>
<td align="right">4.171057</td>
</tr>
<tr class="even">
<td align="left">Some college or AA degree</td>
<td align="right">2406</td>
<td align="right">21.127503</td>
</tr>
<tr class="odd">
<td align="left">NA</td>
<td align="right">6022</td>
<td align="right">52.880225</td>
</tr>
</tbody>
</table>
<pre class="r"><code>race_summary &lt;- obesity %&gt;%
  count(race) %&gt;%
  mutate(Percentage = n / sum(n) * 100)

kable(race_summary, format = &quot;markdown&quot;, caption = &quot;Race Summary&quot;)</code></pre>
<table>
<caption>Race Summary</caption>
<thead>
<tr class="header">
<th align="left">race</th>
<th align="right">n</th>
<th align="right">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Black</td>
<td align="right">2970</td>
<td align="right">26.080084</td>
</tr>
<tr class="even">
<td align="left">Mexican American</td>
<td align="right">1397</td>
<td align="right">12.267299</td>
</tr>
<tr class="odd">
<td align="left">Other</td>
<td align="right">1217</td>
<td align="right">10.686688</td>
</tr>
<tr class="even">
<td align="left">Other Hispanic</td>
<td align="right">1050</td>
<td align="right">9.220232</td>
</tr>
<tr class="odd">
<td align="left">White</td>
<td align="right">3995</td>
<td align="right">35.080787</td>
</tr>
<tr class="even">
<td align="left">NA</td>
<td align="right">759</td>
<td align="right">6.664910</td>
</tr>
</tbody>
</table>
<p>The economic and educational backgrounds of our study group varied,
with significant representation across different races.”</p>
<table>
<caption>Sedentary Activity Summary</caption>
<thead>
<tr class="header">
<th align="right">Count</th>
<th align="right">Mean</th>
<th align="right">Std_Dev</th>
<th align="right">Min</th>
<th align="right">25th_Pctl</th>
<th align="right">Median</th>
<th align="right">75th_Pctl</th>
<th align="right">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">11388</td>
<td align="right">338.351</td>
<td align="right">202.96</td>
<td align="right">0</td>
<td align="right">180</td>
<td align="right">300</td>
<td align="right">480</td>
<td align="right">1320</td>
</tr>
</tbody>
</table>
<pre class="r"><code>bmi_summary &lt;- obesity %&gt;%
  count(bmi) %&gt;%
  mutate(Percentage = n / sum(n) * 100) %&gt;%
  ungroup() 

kable(bmi_summary, format = &quot;markdown&quot;, caption = &quot;BMI Summary&quot;)</code></pre>
<table>
<caption>BMI Summary</caption>
<thead>
<tr class="header">
<th align="left">bmi</th>
<th align="right">n</th>
<th align="right">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">normal</td>
<td align="right">7922</td>
<td align="right">69.56445</td>
</tr>
<tr class="even">
<td align="left">obese</td>
<td align="right">3466</td>
<td align="right">30.43555</td>
</tr>
</tbody>
</table>
<p>Sedentary activity averages around 338 minutes, and approximately 30%
of our study population is categorized as obese.</p>
<pre class="r"><code># Create age groups
obesity &lt;- obesity %&gt;%
  mutate(age_group = case_when(
    age &gt;= 18 &amp; age &lt;= 25 ~ &quot;18-25&quot;,
    age &gt; 25 &amp; age &lt;= 35 ~ &quot;26-35&quot;,
    age &gt; 35 &amp; age &lt;= 45 ~ &quot;36-45&quot;,
    age &gt; 45 &amp; age &lt;= 55 ~ &quot;46-55&quot;,
    age &gt; 55 &amp; age &lt;= 65 ~ &quot;56-65&quot;,
    age &gt; 65 ~ &quot;66+&quot;,
    TRUE ~ &quot;Unknown&quot;
  ))

fast_food_summary &lt;- obesity %&gt;%
  group_by(gender, age_group) %&gt;%
  summarise(Avg_Fast_Food = mean(freq_fast_food, na.rm = TRUE))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;gender&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre class="r"><code>kable(fast_food_summary, format = &quot;markdown&quot;, caption = &quot;Fast Food Frequency Summary by Age Group and Gender&quot;)</code></pre>
<table>
<caption>Fast Food Frequency Summary by Age Group and Gender</caption>
<thead>
<tr class="header">
<th align="left">gender</th>
<th align="left">age_group</th>
<th align="right">Avg_Fast_Food</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">18-25</td>
<td align="right">15.024719</td>
</tr>
<tr class="even">
<td align="left">Female</td>
<td align="left">26-35</td>
<td align="right">2.330855</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">36-45</td>
<td align="right">2.029762</td>
</tr>
<tr class="even">
<td align="left">Female</td>
<td align="left">46-55</td>
<td align="right">2.000000</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">56-65</td>
<td align="right">1.620079</td>
</tr>
<tr class="even">
<td align="left">Female</td>
<td align="left">66+</td>
<td align="right">1.125214</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Unknown</td>
<td align="right">1.794655</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">18-25</td>
<td align="right">2.997696</td>
</tr>
<tr class="odd">
<td align="left">Male</td>
<td align="left">26-35</td>
<td align="right">2.915767</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">36-45</td>
<td align="right">2.457589</td>
</tr>
<tr class="odd">
<td align="left">Male</td>
<td align="left">46-55</td>
<td align="right">2.215190</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">56-65</td>
<td align="right">2.247582</td>
</tr>
<tr class="odd">
<td align="left">Male</td>
<td align="left">66+</td>
<td align="right">1.482982</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Unknown</td>
<td align="right">1.894737</td>
</tr>
</tbody>
</table>
<p>Our analysis of fast food consumption by age and gender shows that
younger females and males aged 18-25 report the highest average
frequency, with a general decline in older age groups.</p>
<pre class="r"><code># Summarize by gender and age group
frozen_food_summary &lt;- obesity %&gt;%
  group_by(gender, age_group) %&gt;%
  summarise(Avg_Frozen_Food = mean(freq_frozen, na.rm = TRUE)) </code></pre>
<pre><code>## `summarise()` has grouped output by &#39;gender&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre class="r"><code>kable(frozen_food_summary, format = &quot;markdown&quot;, caption = &quot;Frozen Food Frequency Summary by Age Group and Gender&quot;)</code></pre>
<table>
<caption>Frozen Food Frequency Summary by Age Group and Gender</caption>
<thead>
<tr class="header">
<th align="left">gender</th>
<th align="left">age_group</th>
<th align="right">Avg_Frozen_Food</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">18-25</td>
<td align="right">2.543260</td>
</tr>
<tr class="even">
<td align="left">Female</td>
<td align="left">26-35</td>
<td align="right">2.370732</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">36-45</td>
<td align="right">2.268489</td>
</tr>
<tr class="even">
<td align="left">Female</td>
<td align="left">46-55</td>
<td align="right">1.764228</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">56-65</td>
<td align="right">1.976257</td>
</tr>
<tr class="even">
<td align="left">Female</td>
<td align="left">66+</td>
<td align="right">1.856436</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Unknown</td>
<td align="right">6.257710</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">18-25</td>
<td align="right">17.747917</td>
</tr>
<tr class="odd">
<td align="left">Male</td>
<td align="left">26-35</td>
<td align="right">15.932170</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">36-45</td>
<td align="right">15.051625</td>
</tr>
<tr class="odd">
<td align="left">Male</td>
<td align="left">46-55</td>
<td align="right">2.060449</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">56-65</td>
<td align="right">2.177396</td>
</tr>
<tr class="odd">
<td align="left">Male</td>
<td align="left">66+</td>
<td align="right">2.253538</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Unknown</td>
<td align="right">17.288692</td>
</tr>
</tbody>
</table>
<p>Similarly, for frozen food, the highest consumption is noted in
younger males, with a notable decrease in older age groups.</p>
<pre class="r"><code># Histogram for BMI
ggplot(obesity, aes(x = bmi)) + 
  geom_histogram(binwidth = 1, fill = &quot;blue&quot;, color = &quot;black&quot;) + 
  labs(title = &quot;Distribution of BMI&quot;, x = &quot;BMI&quot;, y = &quot;Count&quot;) + 
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/data%20distribution%20plots-1.png" width="672" /></p>
<pre class="r"><code># Density plot for BMI
ggplot(obesity, aes(x = bmi)) + 
  geom_density(fill = &quot;blue&quot;, alpha = 0.5) + 
  labs(title = &quot;Density Plot for BMI&quot;, x = &quot;BMI&quot;, y = &quot;Density&quot;) + 
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/data%20distribution%20plots-2.png" width="672" /></p>
<pre class="r"><code># Boxplot for BMI
ggplot(obesity, aes(y = bmi, x = 1)) + 
  geom_boxplot(fill = &quot;blue&quot;, alpha = 0.5) + 
  labs(title = &quot;Boxplot for BMI&quot;, x = &quot;&quot;, y = &quot;BMI&quot;) + 
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/data%20distribution%20plots-3.png" width="672" />
The histogram and density plot indicate that the distribution of
<code>BMI</code> is right-skewed, which is a common observation in
health-related data.</p>
<p>When the response variable in a regression model, BMI, in our case,
is not normally distributed, we took a common approach is to apply a
transformation to achieve normality. The logarithmic transformation is
particularly useful because it is a monotonic transformation that can
handle positive skewness by compressing the long tail and expanding the
lower end of the distribution. This can make the distribution more
symmetric and more closely approximate the normal distribution, which
meets the assumptions of linear regression.</p>
<p>By transforming <code>BMI</code> using the natural logarithm, we can
stabilize the variance (homoscedasticity) and make the relationship
between the predictors and the response variable more linear. This is
beneficial because linear regression assumes a linear relationship
between the predictors and the outcome variable. # Statistical
Analysis</p>
<pre class="r"><code>cv_results |&gt; 
  select(starts_with(&quot;rmse&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;
  ) |&gt; 
  group_by(model_type) |&gt; 
  summarize(m_rmse = mean(rmse))</code></pre>
<pre><code>## # A tibble: 3 × 2
##   model_type    m_rmse
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 fast_adjusted  0.320
## 2 fast_crude     0.477
## 3 fast_inter     0.363</code></pre>
<pre class="r"><code>cv_results |&gt; 
  select(starts_with(&quot;rmse&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;
  ) |&gt; 
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="Report_files/figure-html/model%20comparison-1.png" width="672" />
Analysis of the relationship between fast food consumption and BMI:
First, we used the crossv_mc function to create 100 Monte Carlo
cross-validation splits of the obesity dataset. This approach helps in
assessing the model’s performance more robustly by training and testing
it on different subsets of the data. Then, we constructed three
different models including a fast-food variable as the predictor and
log(bmi) as the outcome for each training set to decide which model was
best fit.</p>
<p>Three models are listed below model_fast_crude: A simple linear
regression model with log(bmi) as the response variable and
freq_fast_food as the predictor. model_fast_adjusted: An adjusted linear
regression model including freq_fast_food and other covariates like age,
gender, marital status, race, education, and income_to_poverty.
model_fast_inter: An interaction model considering interactions between
freq_fast_food and variables such as education and income_to_poverty,
along with the main effects of these predictors.</p>
<div id="model-performance-evaluation" class="section level2">
<h2>Model Performance Evaluation</h2>
<p>After the computation of the RMSE for each model on their test
dataset, the violin plot was made for visualization purposes. This plot
helps in comparing the distribution of RMSEs across the model.
Furthermore, we look at the summary of the Best-Fitting Model. We
extracted and printed the summary of the adjusted model, which is the
best model from the previous step. This summary includes beta
coefficients and p-values. Then, we do the residual analysis for the
adjusted Model. A plot of residuals versus fitted values for the
best_model_fast (adjusted model) was created. This plot is crucial for
diagnosing model fit, as it helps in identifying patterns in the
residuals that might suggest problems with the model, such as
non-linearity or heteroscedasticity.</p>
<p><code>fast_adjusted</code> model has a lower median with most of its
data concentrated at the lower end of the rmse scale, which suggests
better predictive performance for most of its predictions compared to
the other models. The model <code>fast_adjusted</code> seems to be the
best model overall due to its concentration of lower rmse values,
although <code>fast_inter</code> may also perform similarly well for the
majority of predictions but has some predictions with high error.</p>
<p>Best-Fitting Model Analysis</p>
<pre class="r"><code>best_adjusted_model_summary &lt;- cv_results$model_fast_adjusted[[1]] %&gt;% summary()

# Print the summary which includes coefficients, R-squared, p-values...
print(best_adjusted_model_summary)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(bmi) ~ freq_fast_food + age + gender + marital_status + 
##     race + education + income_to_poverty, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.72949 -0.15992 -0.01134  0.15076  0.93870 
## 
## Coefficients:
##                                            Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                               3.432e+00  2.053e-02 167.189  &lt; 2e-16
## freq_fast_food                           -9.807e-05  4.278e-05  -2.292   0.0219
## age                                       3.743e-04  2.763e-04   1.355   0.1756
## genderMale                               -4.479e-02  8.588e-03  -5.216 1.95e-07
## marital_statusNever married              -2.141e-02  1.208e-02  -1.773   0.0764
## marital_statusWidowed/Divorced/Separated -2.121e-02  1.109e-02  -1.913   0.0559
## raceMexican American                     -9.082e-03  1.420e-02  -0.639   0.5226
## raceOther                                -1.714e-01  1.875e-02  -9.140  &lt; 2e-16
## raceOther Hispanic                       -2.224e-02  1.555e-02  -1.431   0.1526
## raceWhite                                -2.832e-02  1.064e-02  -2.662   0.0078
## educationHigh school graduate            -6.437e-03  1.382e-02  -0.466   0.6414
## educationLess than 9th grade             -1.885e-03  2.041e-02  -0.092   0.9264
## educationSome college or AA degree       -3.254e-03  1.355e-02  -0.240   0.8102
## income_to_poverty                         2.728e-03  3.104e-03   0.879   0.3795
##                                             
## (Intercept)                              ***
## freq_fast_food                           *  
## age                                         
## genderMale                               ***
## marital_statusNever married              .  
## marital_statusWidowed/Divorced/Separated .  
## raceMexican American                        
## raceOther                                ***
## raceOther Hispanic                          
## raceWhite                                ** 
## educationHigh school graduate               
## educationLess than 9th grade                
## educationSome college or AA degree          
## income_to_poverty                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2372 on 3159 degrees of freedom
##   (5937 observations deleted due to missingness)
## Multiple R-squared:  0.0362, Adjusted R-squared:  0.03223 
## F-statistic: 9.126 on 13 and 3159 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The estimated <code>log(BMI)</code> is approximately 3.414 when all
predictor variables are held at zero. To interpret this on the original
BMI scale, you would calculate exp(3.414). This value represents the
estimated BMI for the baseline categories of all categorical predictors
(usually the most common or reference category) and zero for continuous
predictors. The coefficient for consumption of the number of meals from
fast food or pizza place is positive (0.00264) and statistically
significant. To interpret the effect on the original BMI scale, consider
that a small increase in the <code>log(BMI)</code> corresponds to a
percentage increase in BMI. Specifically, for each one-unit increase in
fast food consumption, the log(BMI) is expected to increase by 0.0026372
kg/m^2. Similarly, for other continuous predictors like age, the
coefficient represents the percentage change in log(BMI) for a one-unit
increase in that predictor. For categorical predictors like gender,
marital status, and race, the coefficients represent the percentage
difference in log(BMI) compared to the reference category. The
<code>R-squared</code> value (0.02777) indicates that about 2.777% of
the variability in log-transformed BMI is explained by the model. While
this might seem low, it’s not uncommon in behavioral and social science
research where many unmeasured factors can influence the outcome. The
significance of the coefficients suggests that these factors have a
statistically significant association with BMI. However, the magnitude
of these effects might be small, especially for variables like age,
education and income_to_poverty ratio. The significant predictors in the
model, like
<code>freq_fast_food</code>,<code>gender</code>,<code>race</code>
indicate factors that are associated with <code>BMI</code>. However, the
small R-squared value suggests that many other factors not included in
the model also influence <code>BMI</code>. Given that the response
variable is log-transformed, the interpretation is in terms of
percentage change (for continuous predictors) or relative percentage
difference (for categorical predictors) in BMI.</p>
</div>
<div id="histogram-for-sedentary-activity" class="section level2">
<h2>Histogram for Sedentary Activity</h2>
<pre class="r"><code># Histogram and Density Plot for Sedentary Activity
ggplot(obesity, aes(x = sedentary_activity)) +
  geom_histogram(binwidth = 10, fill = &quot;green&quot;, color = &quot;black&quot;, alpha = 0.7) + 
  geom_density(alpha = 0.2, adjust = 1/5) + 
  labs(title = &quot;Distribution of Sedentary Activity&quot;, x = &quot;Sedentary Activity&quot;, y = &quot;Density&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/distribution-1.png" width="672" /></p>
<p>Sedentary lifestyle is a key focus of our study. This histogram
showcases the sedentary activity levels reported by obese individuals.”
Observation: “Most obese individuals report sedentary activity ranging
up to 500 minutes, with the frequency decreasing as activity increases.
Notably, very high levels of sedentary activity are rare.</p>
<pre class="r"><code>cv_results_sedentary |&gt; 
  select(starts_with(&quot;rmse_sed&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_sed_&quot;
  ) |&gt; 
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="Report_files/figure-html/cross%20validation%20comparison-1.png" width="672" /></p>
<pre class="r"><code>rmse_summary = cv_results_sedentary |&gt; 
  select(starts_with(&quot;rmse_sed&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_sed_&quot;
  ) |&gt; 
  group_by(model_type) |&gt; 
  summarize(m_rmse = mean(rmse))
kable(rmse_summary, format = &quot;markdown&quot;, caption = &quot;Summary of RMSE for Sedentary Models&quot;)</code></pre>
<table>
<caption>Summary of RMSE for Sedentary Models</caption>
<thead>
<tr class="header">
<th align="left">model_type</th>
<th align="right">m_rmse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">adjusted</td>
<td align="right">0.2350185</td>
</tr>
<tr class="even">
<td align="left">crude</td>
<td align="right">0.2370175</td>
</tr>
<tr class="odd">
<td align="left">inter</td>
<td align="right">0.2350270</td>
</tr>
</tbody>
</table>
<p>Sedentary activity with log(BMI) - Cross-validation Results In the
context of these models, a lower RMSE indicates a more accurate
prediction of BMI from the predictors used in the model.</p>
<p>The cross-validation results show that the mean RMSE for the adjusted
and inter (interaction) models are both 0.235, while the crude model has
a slightly higher RMSE of 0.237. In this case, both the adjusted and
inter-models perform slightly better than the crude model, as indicated
by their lower RMSE values, which means they are, on average, closer to
the true BMI values when log-transformed.</p>
<p>A valid reason we chose the adjusted model over the inter-model,
despite having the same RMSE, could be its simplicity and
interpretability. The adjusted model includes additional covariates
(age, gender, marital status, race, education, and income-to-poverty
ratio) that are expected to be related to BMI based on previous research
or theoretical considerations. Including these covariates allows the
model to account for more variability in BMI that is explained by these
factors.</p>
<p>Moreover, while interaction terms in the inter-model may capture the
combined effects of sedentary activity with other variables, they can
make the model more complex and harder to interpret. We proceed the
model statistics in the adjusted model for sedentary activity.</p>
</div>
<div id="interpretation-of-the-adjusted-model-sedentary-ativity"
class="section level2">
<h2>Interpretation of the Adjusted model (Sedentary Ativity)</h2>
<pre class="r"><code># Step 1: Generate new data for plotting
new_data &lt;- with(obesity, expand.grid(
  sedentary_activity = seq(min(sedentary_activity, na.rm = TRUE), max(sedentary_activity, na.rm = TRUE), length.out = 100),
  age = mean(age, na.rm = TRUE),
  gender = &quot;Female&quot;, 
  marital_status = &quot;Married&quot;, 
  race = &quot;White&quot;, 
  education = &quot;Less than 9th grade&quot;, 
  income_to_poverty = mean(income_to_poverty, na.rm = TRUE)
))

# Step 2: Predict log(BMI) using the adjusted model and the new data
adjusted_model &lt;- cv_results_sedentary$model_sed_adjusted[[1]]
new_data$log_bmi_pred &lt;- predict(adjusted_model, newdata = new_data)

# Step 3: Create the plot
ggplot(new_data, aes(x = sedentary_activity, y = log_bmi_pred)) +
  geom_line(color = &quot;blue&quot;) +
  labs(title = &quot;Predicted Log BMI vs Sedentary Activity&quot;,
       x = &quot;Sedentary Activity&quot;,
       y = &quot;Predicted Log BMI&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/model%20plot%20for%20adjusted%20model-1.png" width="672" />
Coefficients Interpretation on Log Scale: Intercept: The estimated
log(BMI) is approximately 3.366 when all predictor variables are held at
zero. To interpret this on the original BMI scale, you would calculate
exp(3.366). This value represents the estimated BMI for the baseline
categories of all categorical predictors (usually the most common or
reference category) and zero for continuous predictors.</p>
<p>Sedentary Activity: The coefficient for sedentary activity is
positive (0.0001905) and statistically significant. This suggests that
for each unit increase in sedentary activity, the log(BMI) increases by
this amount. To interpret the effect on the original BMI scale, consider
that a small increase in the log(BMI) corresponds to a percentage
increase in BMI. Specifically, a one-unit increase in sedentary activity
is associated with approximately a 0.01905% increase in BMI.</p>
</div>
<div id="predict-logbmi-using-the-adjusted-model"
class="section level2">
<h2>Predict log(BMI) using the adjusted model</h2>
<p>Other Predictors: Similarly, for other continuous predictors like
age, the coefficient represents the percentage change in BMI for a
one-unit increase in that predictor. For categorical predictors like
gender, marital status, and race, the coefficients represent the
percentage difference in BMI compared to the reference category.</p>
<p>Model Fit and R-squared: The R-squared value (0.06851) indicates that
about 6.851% of the variability in log-transformed BMI is explained by
the model. While this might seem low, it’s not uncommon in behavioral
and social science research, where many unmeasured factors can influence
the outcome.</p>
<p>Statistical Significance: The significance of the coefficients
suggests that these factors have a statistically significant association
with BMI. However, the magnitude of these effects might be small,
especially for variables like age and income_to_poverty ratio.</p>
<p>Overall Interpretation: The significant predictors in the model, like
sedentary activity and gender, indicate factors that are associated with
BMI. However, the small R-squared value suggests that many other factors
not included in the model also influence BMI. Given that the response
variable is log-transformed, the interpretation is in terms of
percentage change (for continuous predictors) or relative percentage
difference (for categorical predictors) in BMI.</p>
</div>
</div>
<div
id="analysis-of-the-relationship-between-frozen-food-consumption-and-bmi"
class="section level1">
<h1>Analysis of the relationship between frozen food consumption and
BMI:</h1>
<p>This model’s aim is to understand how frozen food consumption
potentially influences BMI when controlling for demographic and
socioeconomic factors. I first started generating 100 Monte Carlo
cross-validation splits of the obesity dataset. By doing so, I was able
to evaluate the model’s predictive performance across various subsets of
the data, thereby providing a more reliable assessment of its predictive
capabilities. Three linear regression models were then used for
comparison and analysis</p>
<p>Crude Model: ‘model_frozen_crude’ includes only the frequency of
frozen fast food consumption as a predictor for log-transformed BMI.
Adjusted Model: ‘model_frozen_adjusted’ adjusts for additional
covariates, including age, gender, marital status, race, education, and
income-to-poverty ratio. Interaction Model: ‘model_frozen_inter’
includes interaction terms between frozen fast food frequency and
socioeconomic factors such as education and income-to-poverty ratio,
alongside the main effects.</p>
<div id="model-performance-evaluation-1" class="section level2">
<h2>Model Performance Evaluation</h2>
<pre class="r"><code>cv_results_frozen |&gt; 
  select(starts_with(&quot;rmse_frozen&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_frozen_&quot;
  ) |&gt; 
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>cv_results_frozen |&gt; 
  select(starts_with(&quot;rmse_frozen&quot;)) |&gt; 
  pivot_longer(
    everything(),
    names_to = &quot;model_type&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_frozen_&quot;
  ) |&gt; 
  group_by(model_type) |&gt; 
  summarize(m_rmse = mean(rmse))</code></pre>
<pre><code>## # A tibble: 3 × 2
##   model_type m_rmse
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 adjusted    0.246
## 2 crude       0.308
## 3 inter       0.314</code></pre>
<p>According to the violin plot of the RMSE distribution for each model,
the adjusted model consistently shows a concentrated distribution of
lower RMSE values, meaning it has a superior predictive performance
relative to the crude and interaction models. This observation is
confirmed by the summary of cross-validation results, which indicates
that the adjusted model has the lowest mean RMSE of 0.243, compared to
0.309 for the crude model and 0.336 for the interaction model. Since
lower values mean better model performance, the adjusted model has the
best model performance among these three models.</p>
</div>
<div id="interpretaion-of-adjusted-model" class="section level2">
<h2>Interpretaion of adjusted model</h2>
<pre class="r"><code>adjusted_model_frozen &lt;- cv_results_frozen$model_frozen_adjusted[[1]]
new_data_frozen$log_bmi_pred &lt;- predict(adjusted_model_frozen, newdata = new_data_frozen)

# Plot the predicted values
ggplot(new_data_frozen, aes(x = freq_frozen, y = log_bmi_pred)) +
  geom_line(color = &quot;purple&quot;) +
  labs(title = &quot;Predicted Log BMI vs Frozen Fast Food Frequency&quot;,
       x = &quot;Frozen Fast Food Frequency&quot;,
       y = &quot;Predicted Log BMI&quot;) +
  theme_minimal()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>best_adjusted_model_summary &lt;- cv_results_frozen$model_frozen_adjusted[[1]] %&gt;% summary()

# Print the summary which includes coefficients, R-squared, p-values...
print(best_adjusted_model_summary)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(bmi) ~ freq_frozen + age + gender + marital_status + 
##     race + education + income_to_poverty, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.78970 -0.15881 -0.01053  0.14912  1.09502 
## 
## Coefficients:
##                                            Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                               3.422e+00  1.840e-02 185.913  &lt; 2e-16
## freq_frozen                              -5.845e-05  3.573e-05  -1.636 0.101979
## age                                       2.630e-04  2.462e-04   1.068 0.285465
## genderMale                               -4.409e-02  7.577e-03  -5.819 6.38e-09
## marital_statusNever married              -2.560e-02  1.075e-02  -2.382 0.017280
## marital_statusWidowed/Divorced/Separated -2.170e-02  9.634e-03  -2.252 0.024365
## raceMexican American                     -3.020e-03  1.279e-02  -0.236 0.813283
## raceOther                                -1.751e-01  1.574e-02 -11.121  &lt; 2e-16
## raceOther Hispanic                       -2.595e-02  1.337e-02  -1.941 0.052354
## raceWhite                                -3.229e-02  9.436e-03  -3.422 0.000628
## educationHigh school graduate             1.254e-02  1.191e-02   1.053 0.292502
## educationLess than 9th grade              2.251e-03  1.622e-02   0.139 0.889620
## educationSome college or AA degree        2.544e-02  1.176e-02   2.164 0.030530
## income_to_poverty                        -5.737e-04  2.766e-03  -0.207 0.835727
##                                             
## (Intercept)                              ***
## freq_frozen                                 
## age                                         
## genderMale                               ***
## marital_statusNever married              *  
## marital_statusWidowed/Divorced/Separated *  
## raceMexican American                        
## raceOther                                ***
## raceOther Hispanic                       .  
## raceWhite                                ***
## educationHigh school graduate               
## educationLess than 9th grade                
## educationSome college or AA degree       *  
## income_to_poverty                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2381 on 4079 degrees of freedom
##   (5017 observations deleted due to missingness)
## Multiple R-squared:  0.04143,    Adjusted R-squared:  0.03837 
## F-statistic: 13.56 on 13 and 4079 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Best-Fitting Model Analysis The best-fitting model, based on the
cross-validation results, is the adjusted model. Thus, a detailed
examination was conducted, and its summary statistics indicate that: The
Intercept is estimated at 3.409 on the log scale. The coefficient for
frozen fast food frequency is -4.291e-06 with a p-value of 0.86427, this
suggests that the number of frozen fast food meals consumed does not
have a statistically significant effect on BMI in this model.</p>
<p>Other covariates, such as gender and race, show significant
associations with BMI, with gender (Male) and race (Other) showing a
strong negative association with BMI. The R-squared value of 0.03455
indicates that approximately 3.455% of the variability in the
log-transformed BMI is explained by the model.</p>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>Overall, our analysis suggests that while frozen fast food
consumption frequency does not significantly predict BMI, other factors
such as gender and race do have significant associations. The small
R-squared value implies that other unmeasured factors also play a role
in influencing BMI, which are not captured by this model. The relatively
stable variance in residuals suggests that the linear model is a
reasonable fit for the data, although there is room for improvement.
Future modeling efforts might explore the inclusion of non-linear terms,
additional interaction terms, or other predictor variables to enhance
the model’s explanatory power.</p>
</div>
<div id="data-visualization" class="section level1">
<h1>Data Visualization</h1>
<p>Initial exploratory data analysis involved visualizing the
distribution of sedentary activity within the study population.
Histogram and density plots revealed the spread and central tendency of
sedentary activity levels, which is crucial for identifying the range of
sedentary behaviors in the dataset.</p>
</div>
<div id="regression-analysis" class="section level1">
<h1>Regression Analysis</h1>
<p>A robust statistical approach was employed to predict BMI,
operationalized through a natural logarithmic transformation to achieve
normalization. Three distinct models were constructed to analyze the
relationship: Crude Model: A simple linear regression with sedentary
activity as the sole predictor. Adjusted Model: An extended model
incorporating covariates such as age, gender, marital status, race,
education, and income-to-poverty ratio. Interaction Model: A
sophisticated model considering the interaction between sedentary
activity and covariates like education and income-to-poverty ratio. Each
model was rigorously tested using a 100-fold cross-validation procedure
to ensure the stability and reliability of our findings. Model
Comparison and Selection The comparison of cross-validation results
revealed a slightly superior performance of the adjusted and interaction
models over the crude model, indicated by marginally lower RMSE values
(0.235 vs. 0.237). These results support the hypothesis that sedentary
activity and BMI are linked, and this association is influenced by the
included covariates. The choice of the adjusted model was driven by its
balance of complexity and interpretability, as it significantly accounts
for more variability in BMI while remaining comprehensible.</p>
</div>
<div id="model-statistics" class="section level1">
<h1>Model Statistics</h1>
<p>The regression coefficients from the adjusted model provide insight
into the relationship between each predictor and BMI: Sedentary
Activity: A positive and significant relationship with BMI, though the
effect size is relatively small. Gender: Being male is associated with a
lower BMI compared to females. Marital Status: Being never married or
widowed/divorced/separated shows different associations with BMI
compared to being married. Race: The category ‘Other’ is significantly
associated with lower BMI compared to the reference group. Education:
Attaining some college or AA degree is associated with a higher BMI
compared to the reference education level. The R-squared value of
0.06094, although modest, is not uncommon in behavioral sciences,
indicating that other factors not included in the model also influence
BMI. Residual Analysis The residual plot for the interaction model was
evaluated, revealing a random scatter of residuals around the zero line
with no apparent systematic pattern, indicating a good fit for the
model. The blue LOESS curve is relatively flat and centered around the
horizontal red dashed line, which further corroborates the model’s
appropriateness. ## Detailed Interpretation The coefficients obtained
through regression analysis must be interpreted in the context of a
log-transformed dependent variable. For instance, the coefficient for
sedentary activity (0.0001753) suggests that for each additional unit of
sedentary activity, there is a corresponding 0.01753% increase in BMI,
holding other variables constant. This nuanced interpretation is vital
for understanding the true impact of sedentary behavior on BMI.</p>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>Our findings underscored the significant, albeit modest, influence of
sedentary behavior, on BMI when adjusted for demographic and
socioeconomic factors. The adjusted model’s efficacy in capturing this
relationship provides a compelling narrative about the subtle yet
impactful role of lifestyle choices on personal health metrics such as
BMI.</p>
<p>Furthermore, the linear regression analysis for fast food emphasizes
that the positive and statistically significant coefficient for fast
food consumption underscores the importance of dietary habits in
influencing BMI. While the effect size of fast food consumption on BMI
may seem small, over time or across a population, even small increases
in BMI can have substantial health implications. This analysis could
have a profound influence on policy and the health field. For instance,
the result could inform interventions aimed at reducing fast food
consumption as part of a strategy to combat obesity.</p>
<p>These insights carry significant implications for public health
initiatives. They emphasize the necessity of addressing sedentary
lifestyles and consumption of fast food as part of obesity intervention
strategies. Moreover, the disparities highlighted by demographic
variables like gender and race call for tailored approaches that
consider the socio-cultural dimensions of health.</p>
<p>The nuanced understanding gleaned from our analysis can inform health
policies and programs, enabling them to target interventions more
effectively and contribute to the broader goal of mitigating obesity’s
prevalence and impact.</p>
</div>
<div id="limitations" class="section level1">
<h1>Limitations</h1>
<p>Despite the robust analytical framework employed, our study is not
devoid of limitations:</p>
<p>Transformation Challenges: The use of log-transformed BMI to
normalize the distribution may introduce complexities in interpretation.
The relationship between predictors and the outcome in the transformed
scale does not readily translate to the original BMI scale without
back-transformation.</p>
<p>Model’s Explained Variability: The R-squared values indicated that a
significant proportion of BMI variability remains unexplained by our
models. This suggests the presence of other influential factors not
captured in the analysis, which could range from genetic predispositions
to environmental and behavioral influences.</p>
<p>Causality Constraints: The cross-sectional nature of NHANES data
inhibits our ability to draw causal inferences. Longitudinal studies
would be required to establish causal relationships between lifestyle
factors and BMI.</p>
<p>Potential Confounders: Our models may not have accounted for all
potential confounders, such as mental health status, quality of diet,
metabolic rates, and genetic factors, which could affect the accuracy of
our conclusions.</p>
<p>Heteroscedasticity: If the log transformation did not fully correct
for heteroscedasticity, the standard errors of our estimates might be
biased, leading to unreliable confidence intervals and hypothesis
tests.</p>
<p>Clinical Relevance: The clinical relevance of a log-transformed BMI
may not be as straightforward compared to the traditional BMI categories
used in medical practice.</p>
<p>Generalizability: Our results are based on the U.S. population and
may not be generalizable to other countries or cultures due to
differences in lifestyle, diet, and genetic factors.</p>
</div>
<div id="future-directions" class="section level1">
<h1>Future Directions</h1>
<p>Considering these limitations, future research could:</p>
<p>Incorporate additional variables and potential confounders to capture
a more complete picture of the factors influencing BMI. Utilize
longitudinal data to explore the temporal dynamics of BMI changes in
relation to lifestyle factors. Apply more sophisticated statistical
techniques or machine learning algorithms to better model complex,
non-linear relationships. Extend the analysis to diverse populations to
enhance the generalizability of the findings.</p>
<p>In conclusion, our research contributes valuable insights into the
factors associated with BMI among the obese population in the U.S. It
lays the groundwork for more nuanced public health strategies that can
adapt to the multifaceted nature of obesity. The limitations and
potential avenues for future work highlight the ongoing need for
comprehensive research in this domain.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<ol style="list-style-type: decimal">
<li>Obesity Statistics. Forbes Health. Published January 17, 2023.
Accessed December 8, 2023. <a
href="https://www.forbes.com/health/body/obesity-statistics/"
class="uri">https://www.forbes.com/health/body/obesity-statistics/</a></li>
<li>Tiwari A, Balasundaram P. Public Health Considerations Regarding
Obesity. In: StatPearls. StatPearls Publishing; 2023. Accessed December
8, 2023. <a href="http://www.ncbi.nlm.nih.gov/books/NBK572122/"
class="uri">http://www.ncbi.nlm.nih.gov/books/NBK572122/</a></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
